version: "3"

services:

    rabbitmq:
        image: rabbitmq:3.5.7
        restart: on-failure:5
        ports:
            - 5672
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        volumes:
            - ./:/usr/src/code

    dramatiq:
        build: ./
        command: python manage.py rundramatiq

    web:
        build: ./
        command: python3 manage.py runserver 0.0.0.0:8000 --verbosity 1
        restart: always
        environment:
            DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
            DJANGO_DEBUG: ${DJANGO_DEBUG}
            DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
        ports:
            - 80:8000
        volumes:
            - ./:/usr/src/code
